### ISSUE TITLE
Warn in reports if the proxy lock is not configured correctly

### ISSUE THREAD

**Issue by mudrd8mz** [catalyst/moodle-tool_lockstats#16]
As a part of testing, I added
```
diff --git a/admin/tool/messageinbound/classes/task/pickup_task.php b/admin/tool/messageinbound/classes/task/pickup_task.php
index 1342b6ff9a..e7abf6eba0 100644
--- a/admin/tool/messageinbound/classes/task/pickup_task.php
+++ b/admin/tool/messageinbound/classes/task/pickup_task.php
@@ -48,6 +48,7 @@ class pickup_task extends \core\task\scheduled_task {
      * Execute the main Inbound Message pickup task.
      */
     public function execute() {
+        sleep(350);
         $manager = new \tool_messageinbound\manager();
         return $manager->pickup_messages();
     }
```
When I executed cron.php, I can see it is sleeping there as expected
```
Execute scheduled task: Incoming email pickup (tool_messageinbound\task\pickup_task)
... started 12:32:33. Current memory use 38.5MB.
```
yet there is nothing displayed on the page:

![image](https://user-images.githubusercontent.com/85831/27954563-d558ff52-6310-11e7-9b7d-6d5cd79647e9.png)

**Comment by mudrd8mz** [comment]
... and when that task actually finishes, I would expect it reported. That does not happen either:

![image](https://user-images.githubusercontent.com/85831/27955380-d60e46b0-6314-11e7-835b-cf17ab2376d3.png)

**Comment by mudrd8mz** [comment]
Sorry, my bad. I did not realize there is this configuration step needed to add the proxy log factory. It indeed works well after following it.

**Comment by brendanheywood** [comment]
thanks @mudrd8mz - we have similar config.php setup required for other plugins, and it's easy to test for so I am going to reopen this and make those report pages show a warning when the proxy lock is not configured.

**Comment by mudrd8mz** [comment]
+1 even better, thanks!
