### ISSUE TITLE
Matrix of cron boxes vs pid vs tasks

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_lockstats#2]
Probably the best way of visualising what is running right now, is a table with a row for every task, like the normal scheduled task table, and then a column for every front end. The list of front ends can be autodetected as tasks get run the first time, or as front ends scale up.

In the matrix we'd then highlight each cell which show what fe a task is running on and it would show the pid and how long it has been running for.

We'd probably want a task which runs every day or so and detects which fe records are no longer being used and reap them.

Task | Fe1 | Fe2 | Fe3
--- | --- | --- | -----
foo | | 1 hour | 
forum | 2 min |  | |
blah | |  | 
quiz |  | 1 min | |
blah | | | 10 secs

**Comment by nhoobin** [comment]
This has been implemented.
