### ISSUE TITLE
historyreset.php requires tool_crawler

### ISSUE THREAD

**Issue by mudrd8mz** [catalyst/moodle-tool_lockstats#20]
Clicking the "Reset the lock stastics history" dies with error because of the line
```
require_once($CFG->dirroot .'/admin/tool/crawler/lib.php');
```
I assume it is a forgotten relic from another plugin as I can't see it being used.

**Comment by nhoobin** [comment]
Thanks again for catching this one. I will push a fix shortly.

**Comment by mudrd8mz** [comment]
Thanks. Please do not forget to publish these as new versions in the plugins directory, too.

**Comment by brendanheywood** [comment]
@mudrd8mz on that topic, I really really want to automate that publishing process, you may have seen my comment here:

https://tracker.moodle.org/browse/MDLSITE-4781?focusedCommentId=471810&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-471810

If there is anything we can do to help achieve that, like building the code on the travis side that would push into the plugins dir once the api exists, then we can help.

**Comment by mudrd8mz** [comment]
Yes I am aware of that comment, still have it on my todo list to answer. Thanks for the patience with the current workflow meanwhile.
