### ISSUE TITLE
More details about Ad-hoc tasks

### ISSUE THREAD

**Issue by dmitriim** [catalyst/moodle-tool_lockstats#32]
At the moment some ad-hoc tasks could be found in Slowest tasks  report. But there is no easy way to found out any details about the task.

Would be good to see at least a task class.

![image](https://user-images.githubusercontent.com/4626431/52091568-f0058c00-2608-11e9-97b3-7d38828ef712.png)

Tasks:

* [ ] in current running tasks show the class and lang string for each ad hoc task

**Comment by brendanheywood** [comment]
Yeah this has been in the back of my mind too. Especially since HQ are increasingly breaking up heavy tasks like the forum into lots of smaller ad hoc ones we need better vis of them.

**Comment by brendanheywood** [comment]
@yao9394 next task:

In the lock table:
* [ ] rename 'task' to 'lock'
* [ ] add a component column matching the two task tables
* [ ] add a classname column matching the two task tables
* [ ] add a customdata column (only for adhoc tasks)

In the lock history table:
* [ ] rename 'task' to classname column matching the two task tables
* [ ] add a component column matching the two task tables

* [ ] update the upgrade scripts to 

* [ ] update all the code that reads or writes these to fill and use the new columns

**Comment by brendanheywood** [comment]
@yao9394 mostly whats left is just diplaying data:

* [ ] change 'Current running tasks' to 'Current locks'
* [ ] change 'Task' in the table column header to say 'lock key' - make this a new langauge string as we will use either depending on the context
* [ ] fix the detail.php page (it needs a field rename)
* [ ] link to the detail page from the 'current locks' table 
* [ ] link to the detail page from the 'slowest locks' table 
* [ ] on the detail page, show the 'customdata' column
