### ISSUE TITLE
Clean up potentially frozen locks from the gui

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_lockstats#38]
Sometimes a lock will get frozen, typically when a process has been manually killed, so the db lock has been released but the lockstats code never ran to close the metadata for it.

Add a manual gui button on the detail page, which enables you to clean up a lock using a specific resource key. The way this will work is that given a resource key it will try to first grab that lock with no timeout. If it can, then we instantly release the lock and the existing code should finish up all the metadata. If we cannot grab the lock then that means that the lock is still actually in use somewhere so we shouldn't touch it.

**Comment by ilya-catalyst** [comment]
merged. CLosing
