### ISSUE TITLE
Record and display ad hoc task latency

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_lockstats#39]
We want a nice clean metric which is the delay between when an ad hoc task was supposed to run, vs the time it actually started / completed. 

* [x] make a new 'latency' column in the _locks table
* [x] when an ad hoc task lock is gained populate the latency field with the duration between when it was queued vs when the lock was gained

I think gained latency is the more useful number here rather than released latency. We are less interested specifically in the relative performance of each type of task and more interested in the performance of the overall system.

* [x] in the lock detail page add a new column showing the latency

history:
* [x] in the lock history, add a new columns 'latency'
* [ ] when compressing history update that column. Like duration, this will be the total latency and the average will be determined by dividing by the lockcount on the fly

* [ ] Show a single average ad hoc task latency average for the last day, and last week on the main index page

**Comment by ilya-catalyst** [comment]
Merged. Closing.

Last item will be in different card
