### ISSUE TITLE
Make sql easier to debug with some literal params

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_lockstats#69]
UPDATE mdl_tool_lockstats_locks SET task = $1,gained = $2,released = $3,host = $4,pid = $5 WHERE id=$6

Very occasionally we want to see what exactly is locked, I am assuming the lock api call is inside a transaction, so the update is locked until the transaction finishes. This is where we should probably use a second connection (https://github.com/catalyst/moodle-tool_lockstats/issues/35). But just getting visibility would help so I'm thinking just the 'task' param gets removed and turned into a string literal in the sql statement. We may need to do this is 2-3 places

**Comment by ilya-catalyst** [comment]
merged. Closing
