### ISSUE TITLE
SQL Error on adhoc_tasks.php 141

### ISSUE THREAD

**Issue by joshwillcock** [catalyst/moodle-tool_lockstats#79]
Hello,

 Added this plugin mainly to learn how Scheduled Tasks get distributed on a cluster. But I am getting an error on a fresh install:
`You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'ON (classes.classname)
classes.classname,
cl' at line 1`...

Before I look into deeply at resolving this, is this plugin supposed to be compatible with MariaDB & Moodle 3.5?

Thanks

**Comment by brendanheywood** [comment]
@joshwillcock are you able to test that patch above?

**Comment by brendanheywood** [comment]
should be already fixed
