### ISSUE TITLE
Failed adhoc tasks are not shown as failed

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_lockstats#98]
![image](https://user-images.githubusercontent.com/187449/82848075-23bea080-9f35-11ea-9852-ade8749e1ac6.png)

but all 4 of these are maxed out busted tasks:

![image](https://user-images.githubusercontent.com/187449/82848102-536da880-9f35-11ea-8da7-afda12c35a66.png)

This *should* have shown the issues we found the other day:

https://tracker.moodle.org/browse/MDL-68769
https://tracker.moodle.org/browse/MDL-68773
https://tracker.moodle.org/browse/MDL-68774

**Comment by Peterburnett** [comment]
These tasks do not show up as failed when lockstats is not enabled. When lockstats is properly enabled and working, these show as failed.
